env_path: ~/.env
container_name: redmine
docker_image: redmine:latest

docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io

docker_packages_state: present
docker_service_manage: false
docker_service_state: started
docker_service_enabled: true
docker_restart_handler_state: restarted

# upmon
upmon_url: "{{ vault_upmon_url }}"

# datadog
datadog_agent_flavor: "datadog-agent"
datadog_api_key: "{{ vault_dd_api_key}}"
datadog_site: "datadoghq.eu"
datadog_checks:
  http_check:
    init_config:
    instances:
      - name: Redmine
        url: http://0.0.0.0
        timeout: 5
        tags:
          - redmine
        collect_response_time: true
