roles:
  - name: geerlingguy.pip
    version: 3.1.0

  - name: geerlingguy.docker
    version: 7.4.7

  - name: datadog.datadog
    version: 4.28.0

  - name: nginxinc.nginx
    version: 0.25.0

collections:
  - name: community.general
